#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: workflow_1
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main